### ISSUE TITLE
Finalización de la práctica

### ISSUE THREAD

**Issue by Franxobass** [interfacesweb-19-20/guia-estilos-Franxobass#1]
Ya he finalizado la práctica @pedroprieto.

Me ha surgido una duda. Resulta que yo para los css suelo trabajar con scss (ya sé que no es necesario, pero me resulta más cómodo) y quisiera saber si hay alguna forma de cuando haces push que no se añadan al repositorio.

**Comment by pedroprieto** [comment]
Buenas,
Perfecto. Sin ningún problema.

Para evitar que se añadan archivos al repositorio tienes que crear un archivo `.gitignore` en el mismo y en su interior poner los archivos a ignorar. En tu caso tienes que tener una línea que sea:
```
*.scss
```

De esta manera los archivos con extensión `.scss` no se añadirán cuando ejecutes `git add`.

Como ya tienes uno dentro del repositorio, tendrás que sacarlo y hacer un nuevo `commit`. Tienes más información aquí: https://stackoverflow.com/questions/7927230/remove-directory-from-remote-repository-after-adding-them-to-gitignore/19681991#answer-7927283

**Comment by Franxobass** [comment]
No es exactamente lo que pensaba, puesto que me gustaría tener un control de versiones de los archivos scss. En realidad es para evitar que se suban al servidor al hacer push. Pero lo investigaré por mi cuenta.

Ya puedes cerrar la tarea

**Comment by pedroprieto** [comment]
Entonces, ¿lo que quieres es tener los archivos scss en el control de versiones local pero que no se suban al hacer push? Ese caso no es posible, me temo. Ten en cuenta que el repositorio remoto es una copia exacta del local al hacer un push.
Si tienes más dudas sobre el tema vuelve a comentar y abre el issue de nuevo.
Un saludo!
